# Generated by Django 4.2.10 on 2024-03-11 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('paymentMethod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fundRaised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical', 'medical'), ('emergency', 'emergency'), ('Education', 'Education'), ('startUps', 'startUps'), ('charity', 'charity')], default='charity', max_length=29)),
                ('fund_for', models.CharField(choices=[('someoneElse', 'someoneElse'), ('yourself', 'yourself'), ('charity', 'charity')], default='yourself', max_length=29)),
                ('goal', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='stories/')),
                ('title', models.TextField(max_length=10, unique=True)),
                ('story', models.TextField(max_length=100)),
                ('present_fund', models.IntegerField(default=0)),
                ('NoDonations', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='successStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv', models.FileField(upload_to='stories/')),
                ('funds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fundraised')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='donations',
            name='funds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fundraised'),
        ),
        migrations.AddField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
